default: &default
  adapter: mysql2
  encoding: utf8
  username: root

development:
  <<: *default
  database: brownlum_development

test:
  <<: *default
  database: brownlum_test

production:
  <<: *default
  username: brownlum_rails
  password: brownlumber
